language: php
sudo: required
services:
  - docker

before_install:
  - docker build -t php/eight -f Dockerfile.dev .

script:
  - docker run -it -v $(pwd):/var/www/html php/eight composer install
  - docker run -it -v $(pwd):/var/www/html php/eight vendor/bin/phpunit