version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - .:/var/app/staging

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - .env
